Automatically update credits file with latest licence information
OctopusDeploy/docs pull request #2385
Opened 2024-07-19 09:06 UTC by Octobob

This is an automated update of the credits / license attribution file, based on the latest code in https://github.com/OctopusDeploy/OctopusDeploy.

Please review for

- syntactical correctness (ie, markdown looks correct)
- logical correctness (ie, when reading it, it makes sense)
- license conformance (we agree with the license in question and we are able to redistribute it)

This pull request was created by TeamCity project TeamCorePlatform_AutomatedDocumentationUpdates build 13143033

2024-07-23 23:32 UTC, michaelnoonan approved these changes

2025-08-19 07:28 UTC, jburger requested changes
I think we need to reconcile some of the esoteric licenses that have cropped up recently. cc @michaelnoonan

2025-08-19 07:28 UTC, jburger commented on docs/credits.md
>  | path-is-inside                                    | Domenic Denicola                                                          | [https://github.com/domenic/path-is-inside](https://github.com/domeni
@michaelnoonan WTFPL detected xD. I think this might be against policy https://octopushq.atlassian.net/wiki/spaces/RND/pages/3108765730/Using+Open+Source+in+Octopus+projects (change at line 1345)

2025-08-19 07:28 UTC, jburger commented on docs/credits.md
> +| path-scurry                                       | Isaac Z. Schlueter                                                        | [https://github.com/isaacs/path-scurry](https://github.com/isaacs/pat
I'm sure this one is OK in principle, however it's not listed as approved here: https://octopushq.atlassian.net/wiki/spaces/RND/pages/3108765730/Using+Open+Source+in+Octopus+projects

2025-08-19 23:44 UTC, andrewabest commented on docs/credits.md
>  | path-is-inside                                    | Domenic Denicola                                                          | [https://github.com/domenic/path-is-inside](https://github.com/domeni
```
  is-path-inside@2.1.0:
    dependencies:
      path-is-inside: 1.0.2
```

Just Npm Things. It looks like it is ultimately a dependency of eslint, so isn't a production dependency.

2025-08-22 11:50 UTC, steve-fenton-octopus commented
FYI: There are some links being generated with a leading `+`, which means they don't make the test suite happy as they don't work.

For example:

`+https:/github.com/swc-project/plugins`

2025-08-29 09:32 UTC, Steve-Fenton commented on docs/credits.md
> +| @swc/plugin-emotion                               | 강동윤                                                                       | [+https://github.com/swc-project/plugins](+https://github.com/swc-pro
@borland is there any way of preventing this nasty `+` signs being included in links? It makes the link behave oddly. I don't know what is different about some of these dependencies that causes it, but if we can strip them out the links would work.

2025-08-29 10:22 UTC, borland commented on docs/credits.md
> +| @swc/plugin-emotion                               | 강동윤                                                                       | [+https://github.com/swc-project/plugins](+https://github.com/swc-pro
I hadn't seen those! easy to miss in the giant file.

Looking at [the swc-project github repo](https://github.com/search?q=repo%3Aswc-project%2Fplugins%20%2Bhttps&type=code) they have things like `"url": "git+https://github.com/swc-project/plugins.git"`

This is not any kind of valid URL, perhaps it's a thing specific to node/swc packages, or perhaps they just made it up. There's a couple of other `git+https` license URL's for other packages too.

The thing which generates this MD file is code we wrote, so now that we have an idea that it exists and where it comes from, I'm sure we can update the tooling to fix it up. I'll chuck a task on our team's list, we should hopefully get to it Monday or Tuesday

Cheers

2025-08-29 10:23 UTC, borland commented on docs/credits.md
> +| @swc/plugin-emotion                               | 강동윤                                                                       | [+https://github.com/swc-project/plugins](+https://github.com/swc-pro
https://app.shortcut.com/octopusdeploy/story/120073/credits-file-generator-needs-to-fix-git-https-urls-for-npm-packages

2025-08-29 15:04 UTC, jburger commented on docs/credits.md
> +| path-scurry                                       | Isaac Z. Schlueter                                                        | [https://github.com/isaacs/path-scurry](https://github.com/isaacs/pat
We've had the legal team assess these outliers and have the all clear on the BlueOak license

2025-08-29 15:29 UTC, Steve-Fenton commented on docs/credits.md
> +| @swc/plugin-emotion                               | 강동윤                                                                       | [+https://github.com/swc-project/plugins](+https://github.com/swc-pro
```suggestion
| @swc/plugin-emotion                               | 강동윤                                                                       | [https://github.com/swc-project/plugins](https://github.com/swc-project/plugins)                                                                                                                                          | [Apache-2.0](https://spdx.org/licenses/Apache-2.0.html)                                                             |
```

2025-09-01 07:35 UTC, merged